### ISSUE TITLE
IP-cycle

### ISSUE THREAD

**Issue by ivailop** [s2testorg/hello#7]
```
testspace:
  branch: "hello" # optional, defaults to "master"
  specs: # optional one or more relative to the .testspace.yml "path" property
    - path: "specs"
      ignore: "hello*" # optional one or more git-ignore wildcard patterns
    - path: "/yml-rel-path/to/file.md"
```
